name: Hardhat CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Compile contracts
        run: npx hardhat compile

    #   - name: Run Solidity linter (solhint)
    #     run: npx solhint 'contracts/**/*.sol'
      - name: Run Solidity linter (hardhat-solhint)
        run: npx hardhat check
      
  
      - name: Run Hardhat tests
        run: npx hardhat test
